### ISSUE TITLE
Does this need to be a var?

### ISSUE THREAD

**Issue by bwmcadams** [spice-labs-inc/goatrodeo#3]
The atomic boolean should be mutating internally; there shouldn't be a need for a mutable referrence.

Correct me if I'm wrong.

https://github.com/spice-labs-inc/goatrodeo/blob/b25c46ceedced228cd13dfad985428e63b360068/src/main/scala/goatrodeo/omnibor/Builder.scala#L88

**Comment by dpp** [comment]
Resolved in slim branch which has been merged into main
